apiVersion: v1
kind: Pod
metadata:
  name: memory-cpu
spec:
  containers:
  - name: memory-cpu
    image: polinux/stress
    resources:
      requests:
        cpu: "250m"
        memory: "100Mi"
      limits:
        cpu: "500m"
        memory: "200Mi"
    command: ["stress"]
    args: ["--vm", "1", "--vm-bytes", "150M", "--vm-hang", "1"]

