apiVersion: v1
kind: Pod
metadata:
  name: cm-pod-env
spec:
  containers:
    - name: env-container
      image: nginx
      env:
      - name: ENV_VAR1
        valueFrom:
          configMapKeyRef:
            name: env-config-yaml
            key: ENV_VAR1
      - name: ENV_VAR2
        valueFrom:
          configMapKeyRef:
            name: env-config-yaml
            key: ENV_VAR2
  restartPolicy: Never
