apiVersion: v1
kind: Pod
metadata:
  name: cm-pod-arg
spec:
  containers:
    - name: test-container
      image: k8s.gcr.io/busybox
      command: [ "/bin/sh", "-c", "echo $(ENV_VARIABLE_1) and $(ENV_VARIABLE_2)" ]
      env:
      - name: ENV_VAR1
        valueFrom:
          configMapKeyRef:
            name: env-config-yaml
            key: ENV_VAR1
      - name: ENV_VAR2
        valueFrom:
          configMapKeyRef:
            name: env-config-yaml
            key: ENV_VAR2
  restartPolicy: Never

